### PR TITLE
fix notes - special characters

### PR DESCRIPTION
**Pull request by Artaud**
Fix mainly for special characters present in notes that would not stop the execution of the script, but the resulting csv would not get imported successfully to Sleep as Android.

### CODE REVIEW

**Comment by VeryCrazyDog** [comment]
Thanks. However I don't quite agree the way to replace the character by some other characters. Anyway I will merge the pull request first and revise it.

**Comment by VeryCrazyDog** [comment]
@Artaud Would you mind share your Sleepbot exported files which contains the special characters for my further study? I can sure install Sleepbot, add some special characters and export it to generate the testing file, but I am lazy 😛

**Comment by Artaud** [comment]
Hi @VeryCrazyDog, thanks for the merge. 
This was kinda a quick hack since I was asked by one of our users (I'm with Urbandroid) to help her with your script, so I figured it could help others as well, but didn't really have too much time for perfecting the script :) I'm sure you know what I mean.

Unfortunately I can't really send you the exact SleepBot csv I was using since I promised not to share them due to their personal nature.

I believe it could be alright if I sent you an excerpt, one note that contained the chars preventing successful import. Could you please contact me at jiri.richter@urbandroid.org and I'll send you an email?

**Comment by VeryCrazyDog** [comment]
@Artaud I sent you an email, hope you have received it and share me an excerpt for my further checking, thanks.

**Pull request merged**
